### ISSUE TITLE
How to train on each dataset?

### ISSUE THREAD

**Issue by OUTSIDER-CODE** [lsy0882/RDFA-S6#1]
Firstly, thanks your work on this issue and I'm really interested in your work. 
But I find the dataste's featutes are not provided, so could you provided some relevant information to help me have a better understanding in your work?
Additionally, apart from the features, how to train the model through the code?
looking forward to your reply,thanks

**Comment by lsy0882** [comment]
Apologies for the delayed response.
We used the dataset features provided in the ActionMamba paper for our research.
